// Auto-generated by GraphQL Codegen — do not edit manually.
// Manually maintained to match real backend schema (NestJS bundled on Lambda — input type names are minified).
// Use scalar variable types in GQL strings (never reference input type names like LoginInput).

export type Maybe<T> = T | null
export type Scalars = {
  ID: { input: string; output: string }
  String: { input: string; output: string }
  Boolean: { input: boolean; output: boolean }
  Int: { input: number; output: number }
  Float: { input: number; output: number }
  DateTime: { input: string; output: string }
}

// ─── Enums ───────────────────────────────────────────────────────────────────

export type UserRole = 'admin' | 'user'

export type OrderStatus =
  | 'PENDING'
  | 'CONFIRMED'
  | 'PROCESSING'
  | 'SHIPPED'
  | 'DELIVERED'
  | 'CANCELLED'

// ─── Core entity types ────────────────────────────────────────────────────────

export type Address = {
  __typename?: 'Address'
  id: string
  street: string
  city: string
  country: string
  postalCode?: string | null
  isDefault: boolean
  createdAt: string
}

export type User = {
  __typename?: 'User'
  id: string
  email: string
  name: string
  role: UserRole
  createdAt: string
  updatedAt: string
  addresses: Address[]
}

export type AuthPayload = {
  __typename?: 'AuthPayload'
  accessToken: string
  user: User
}

export type Category = {
  __typename?: 'Category'
  id: string
  name: string
  description?: string | null
  isActive: boolean
  parent?: Category | null
  children?: Category[] | null
}

export type Product = {
  __typename?: 'Product'
  id: string
  name: string
  description?: string | null
  price: number
  stock: number
  categoryId: string
  category: Category
  imageKeys: string[]
  imageUrls: string[]
  isActive: boolean
  createdAt: string
  updatedAt: string
  relatedProducts?: Product[] | null
  averageRating?: number | null
  reviewCount?: number | null
}

export type CartItem = {
  __typename?: 'CartItem'
  productId: string
  quantity: number
  subtotal: number
  product?: Product | null
}

export type CartType = {
  __typename?: 'Cart'
  total: number
  items: CartItem[]
}

export type OrderItem = {
  __typename?: 'OrderItem'
  id: string
  orderId: string
  productId: string
  quantity: number
  unitPrice: number
}

export type Order = {
  __typename?: 'Order'
  id: string
  userId: string
  status: OrderStatus
  totalAmount: number
  shippingAddressId?: string | null
  items: OrderItem[]
  createdAt: string
  updatedAt: string
}

export type UploadUrlPayload = {
  __typename?: 'UploadUrlPayload'
  uploadUrl: string
  key: string
}

export type PaginatedProducts = {
  __typename?: 'PaginatedProducts'
  items: Product[]
  total: number
  hasMore: boolean
}

// ─── Review types ────────────────────────────────────────────────────────────

export type Review = {
  __typename?: 'Review'
  id: string
  userId: string
  productId: string
  orderId: string
  rating: number
  comment?: string | null
  createdAt: string
  updatedAt: string
}

export type GetProductReviewsQuery = {
  __typename?: 'Query'
  productReviews: Review[]
}

export type GetProductReviewsQueryVariables = {
  productId: string
  limit?: number | null
  offset?: number | null
}

export type CreateReviewMutation = {
  __typename?: 'Mutation'
  createReview: Review
}

export type CreateReviewMutationVariables = {
  productId: string
  orderId: string
  rating: number
  comment?: string | null
}

export type UpdateReviewMutation = {
  __typename?: 'Mutation'
  updateReview: Review
}

export type UpdateReviewMutationVariables = {
  id: string
  rating: number
  comment?: string | null
}

export type DeleteReviewMutation = {
  __typename?: 'Mutation'
  deleteReview: boolean
}

export type DeleteReviewMutationVariables = {
  id: string
}

// ─── Wishlist types ───────────────────────────────────────────────────────────

export type WishlistItem = {
  __typename?: 'WishlistItem'
  id: string
  userId: string
  productId: string
  createdAt: string
}

export type GetMyWishlistQuery = {
  __typename?: 'Query'
  myWishlist: Product[]
}

export type GetMyWishlistQueryVariables = Record<string, never>

export type AddToWishlistMutation = {
  __typename?: 'Mutation'
  addToWishlist: boolean
}

export type AddToWishlistMutationVariables = {
  productId: string
}

export type RemoveFromWishlistMutation = {
  __typename?: 'Mutation'
  removeFromWishlist: boolean
}

export type RemoveFromWishlistMutationVariables = {
  productId: string
}

// ─── Auth mutations ───────────────────────────────────────────────────────────

export type LoginMutation = {
  __typename?: 'Mutation'
  login: AuthPayload
}

/** Scalar vars only — NestJS bundles minify input type names */
export type LoginMutationVariables = {
  email: string
  password: string
}

export type RegisterMutation = {
  __typename?: 'Mutation'
  register: AuthPayload
}

/** Scalar vars only — NestJS bundles minify input type names */
export type RegisterMutationVariables = {
  name: string
  email: string
  password: string
}

// ─── Product queries / mutations ──────────────────────────────────────────────

export type GetProductsQuery = {
  __typename?: 'Query'
  products: PaginatedProducts
}

export type GetProductsQueryVariables = {
  limit: number
  offset: number
  categoryId?: string | null
  search?: string | null
  sortBy?: string | null
  sortOrder?: string | null
}

export type GetProductQuery = {
  __typename?: 'Query'
  product: Product
}

export type GetProductQueryVariables = {
  id: string
}

export type CreateProductMutation = {
  __typename?: 'Mutation'
  createProduct: Product
}

export type CreateProductMutationVariables = {
  name: string
  description?: string | null
  price: number
  stock: number
  categoryId: string
  imageKeys: string[]
}

export type UpdateProductMutation = {
  __typename?: 'Mutation'
  updateProduct: Product
}

export type UpdateProductMutationVariables = {
  id: string
  name?: string | null
  description?: string | null
  price?: number | null
  stock?: number | null
  categoryId?: string | null
  imageKeys?: string[] | null
  isActive?: boolean | null
}

export type RemoveProductMutation = {
  __typename?: 'Mutation'
  removeProduct: boolean
}

export type RemoveProductMutationVariables = {
  id: string
}

// ─── Category queries / mutations ─────────────────────────────────────────────

export type GetCategoriesQuery = {
  __typename?: 'Query'
  categories: Category[]
}

export type GetCategoriesQueryVariables = Record<string, never>

export type GetCategoryQuery = {
  __typename?: 'Query'
  category: Category
}

export type GetCategoryQueryVariables = {
  id: string
}

export type CreateCategoryMutation = {
  __typename?: 'Mutation'
  createCategory: Category
}

export type CreateCategoryMutationVariables = {
  name: string
  description?: string | null
  parentId?: string | null
}

export type UpdateCategoryMutation = {
  __typename?: 'Mutation'
  updateCategory: Category
}

export type UpdateCategoryMutationVariables = {
  id: string
  name?: string | null
  description?: string | null
  isActive?: boolean | null
}

export type RemoveCategoryMutation = {
  __typename?: 'Mutation'
  removeCategory: boolean
}

export type RemoveCategoryMutationVariables = {
  id: string
}

// ─── Address queries / mutations ─────────────────────────────────────────────

export type GetMyAddressesQuery = {
  __typename?: 'Query'
  myAddresses: Address[]
}

export type GetMyAddressesQueryVariables = Record<string, never>

export type AddAddressMutation = {
  __typename?: 'Mutation'
  addAddress: Address
}

export type AddAddressMutationVariables = {
  street: string
  city: string
  country: string
  postalCode?: string | null
  isDefault: boolean
}

export type UpdateAddressMutation = {
  __typename?: 'Mutation'
  updateAddress: Address
}

export type UpdateAddressMutationVariables = {
  id: string
  street?: string | null
  city?: string | null
  country?: string | null
  postalCode?: string | null
  isDefault?: boolean | null
}

export type RemoveAddressMutation = {
  __typename?: 'Mutation'
  removeAddress: boolean
}

export type RemoveAddressMutationVariables = {
  id: string
}

export type SetDefaultAddressMutation = {
  __typename?: 'Mutation'
  setDefaultAddress: Address
}

export type SetDefaultAddressMutationVariables = {
  id: string
}

// ─── Cart queries / mutations ─────────────────────────────────────────────────

export type GetMyCartQuery = {
  __typename?: 'Query'
  myCart: CartType
}

export type GetMyCartQueryVariables = Record<string, never>

export type AddToCartMutation = {
  __typename?: 'Mutation'
  addToCart: boolean
}

export type AddToCartMutationVariables = {
  productId: string
  quantity: number
}

export type RemoveFromCartMutation = {
  __typename?: 'Mutation'
  removeFromCart: boolean
}

export type RemoveFromCartMutationVariables = {
  productId: string
}

export type UpdateCartItemQuantityMutation = {
  __typename?: 'Mutation'
  updateCartItemQuantity: boolean
}

export type UpdateCartItemQuantityMutationVariables = {
  productId: string
  quantity: number
}

// ─── Order queries / mutations ────────────────────────────────────────────────

export type GetMyOrdersQuery = {
  __typename?: 'Query'
  myOrders: Order[]
}

export type GetMyOrdersQueryVariables = Record<string, never>

export type GetMyOrderQuery = {
  __typename?: 'Query'
  myOrder: Order
}

export type GetMyOrderQueryVariables = {
  id: string
}

export type PlaceOrderMutation = {
  __typename?: 'Mutation'
  placeOrder: Order
}

export type PlaceOrderMutationVariables = {
  shippingAddressId: string
}

export type UpdateOrderStatusMutation = {
  __typename?: 'Mutation'
  updateOrderStatus: {
    __typename?: 'Order'
    id: string
    status: OrderStatus
  }
}

export type UpdateOrderStatusMutationVariables = {
  id: string
  status: OrderStatus
}

export type CancelMyOrderMutation = {
  __typename?: 'Mutation'
  cancelMyOrder: Order
}

export type CancelMyOrderMutationVariables = {
  id: string
}

export type GetOrdersQuery = {
  __typename?: 'Query'
  orders: Order[]
}

export type GetOrdersQueryVariables = {
  status?: OrderStatus | null
  userId?: string | null
  limit?: number | null
  offset?: number | null
}

// ─── User queries ─────────────────────────────────────────────────────────────

export type MeQuery = {
  __typename?: 'Query'
  me: User
}

export type MeQueryVariables = Record<string, never>

export type GetUsersQuery = {
  __typename?: 'Query'
  users: User[]
}

export type GetUsersQueryVariables = Record<string, never>

// ─── Upload ───────────────────────────────────────────────────────────────────

export type RequestUploadUrlMutation = {
  __typename?: 'Mutation'
  requestProductUploadUrl: UploadUrlPayload
}

export type RequestUploadUrlMutationVariables = {
  filename: string
  contentType: string
}
